[package]
name = "snappy"
version = "0.1.0"
authors = ["Rivtower Technologies <contact@rivtower.com>"]
description = "A library provide compress method"
license = "Apache-2.0"
edition = "2018"

[dependencies]
libc = "0.2.101"
